export default {
  CREATE_ROOM: 'CREATE_ROOM',
  CREATE_USER: 'CREATE_USER',
  ADD_USERS: 'ADD_USERS',
  GET_ROOM: 'GET_ROOM',
  SET_SELECTED: 'SET_SELECTED',
  REMOVE_USER: 'REMOVE_USER',
  ADD_MESSAGE: 'ADD_MESSAGE',
  ADD_VALUE: 'ADD_VALUE',
  DROP_VALUES: 'DROP_VALUES',
  ADD_EXTRAVALUES: 'ADD_EXTRAVALUES'
}
